Add config to Text Api location
microsoft/SynapseML pull request #1235
Opened 2021-11-02 11:40 UTC by stuartleeks

Adds `TEXT_API_LOCATION` environment variable (defaults to `eastus`) to allow overriding the Cognitive Services, alongside the existing `TEXT_API_KEY`.

2021-11-02 17:01 UTC, mhamilton723 requested changes
Love it! One minor change!

2021-11-02 19:44 UTC, stuartleeks commented on cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
> +trait TextApiLocation {
Yup, that went through my mind, but then I wasn't sure what the name of the trait should be as `TextKey` is no longer descriptive. Maybe `TextEndpoint` as a combination of location + key?

2021-11-02 19:51 UTC, stuartleeks commented on cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
> +trait TextApiLocation {
Just pushed a commit that combines `TextKey` and `TextApiLocation` into a single `TextEndpoint` trait

2021-11-05 17:02 UTC, mhamilton723 commented
/azp run

2021-11-08 17:35 UTC, merged