feat: add Form Recognizer V3.0
microsoft/SynapseML pull request #1269
Opened 2021-11-23 08:24 UTC by serena-ruan

2021-11-29 06:38 UTC, serena-ruan commented
/azp run

2022-01-29 06:52 UTC, serena-ruan commented
Pending on form recognizer team fixing custom model of V3.0

2022-03-01 03:36 UTC, serena-ruan commented
/azp run

2022-03-01 05:36 UTC, serena-ruan commented
/azp run

2022-03-01 07:22 UTC, serena-ruan commented
/azp run

2022-03-02 05:36 UTC, mhamilton723 requested changes
Wooo woo! Looking awesome! A few nits and a rename request. Also we should remember to put this in website Transformers section, though feel free to do in follow up

2022-03-02 05:36 UTC, mhamilton723 commented on cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormRecognizerV3.scala
> +      val base = getUrl + s"${getValue(row, prebuiltModelId)}:analyze?api-version=2021-09-30-preview"
nit, perhaps make api_version a param with this as default

2022-03-02 05:36 UTC, mhamilton723 commented on cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormRecognizerV3.scala
> +class AnalyzeDocumentV3(override val uid: String) extends CognitiveServicesBaseNoHandler(uid)
are we able to call this AnalyzeDocument and rename previous to AnalyzeDocumentV2? Thats what we did for TA update

2022-03-02 05:36 UTC, mhamilton723 commented on cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FormRecognizerV3Suite.scala
> +    resultAssert(result1, "Contoso\nContoso\n123 Main Street\nRedmond, WA 98052\n123-456-7890\n" +
nit: theres a bit of duplication in these tests (each assert happens twice), perhaps there's a nice way to reduce copy-paste here. Dont spend too much time worrying about it though :)

2022-03-03 09:10 UTC, serena-ruan commented
/azp run

2022-03-04 18:13 UTC, mhamilton723 approved these changes
What a hero PR

2022-03-07 03:18 UTC, merged