feat: add mlflow support for SynapseML models
microsoft/SynapseML pull request #1277
Opened 2021-11-29 09:36 UTC by serena-ruan

2021-11-30 08:29 UTC, serena-ruan commented
/azp run

2021-11-30 08:35 UTC, imatiach-msft submitted a review, later dismissed
This is awesome!!  Does this resolve the issue https://github.com/microsoft/SynapseML/issues/1275 ?
Can you add a description to the PR?  Thank you!

2021-11-30 08:40 UTC, serena-ruan commented
> This is awesome!! Does this resolve the issue #1275 ? Can you add a description to the PR? Thank you!

Oh yes! This looks relevant! we could support log_model in the PR as well to solve that issue.

2021-11-30 08:56 UTC, serena-ruan commented
/azp run

2021-12-03 09:45 UTC, serena-ruan commented
/azp run

2021-12-06 08:14 UTC, serena-ruan commented
/azp run

2021-12-08 11:34 UTC, serena-ruan commented
/azp run

2021-12-08 11:57 UTC, serena-ruan commented
/azp run

2021-12-09 06:12 UTC, serena-ruan commented
/azp run

2021-12-17 18:44 UTC, mhamilton723 requested changes

2021-12-17 18:44 UTC, mhamilton723 commented on core/src/main/scala/com/microsoft/azure/synapse/ml/isolationforest/IsolationForest.scala
> +      new IsolationForestModel(uid).setInnerModel(that.fit(data).setPredictionCol("prediction"))
this should be set with the estimator's prediction cog

2021-12-31 04:53 UTC, imatiach-msft submitted a review, later dismissed

2022-01-04 08:56 UTC, serena-ruan commented
/azp run

2022-01-04 09:14 UTC, serena-ruan commented
/azp run

2022-01-06 04:12 UTC, mhamilton723 approved these changes

2022-01-06 04:12 UTC, mhamilton723 approved these changes

2022-01-06 04:12 UTC, mhamilton723 commented
/azp run

2022-01-06 06:47 UTC, merged